// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_aU9Vlj0nBABHj-akncyMoRnFbgnwx9U',
    appId: '1:773624019931:web:6920e872af2088392e05fe',
    messagingSenderId: '773624019931',
    projectId: 'journee-flutter',
    authDomain: 'journee-flutter.firebaseapp.com',
    storageBucket: 'journee-flutter.appspot.com',
    measurementId: 'G-23J4EQ92GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqXceOOhEG5I9h66MtdBHiofM_Cq-V3M0',
    appId: '1:773624019931:android:3ff3b7fa0730ec4d2e05fe',
    messagingSenderId: '773624019931',
    projectId: 'journee-flutter',
    storageBucket: 'journee-flutter.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_aU9Vlj0nBABHj-akncyMoRnFbgnwx9U',
    appId: '1:773624019931:web:62747a2a866148132e05fe',
    messagingSenderId: '773624019931',
    projectId: 'journee-flutter',
    authDomain: 'journee-flutter.firebaseapp.com',
    storageBucket: 'journee-flutter.appspot.com',
    measurementId: 'G-GEC8R6EETV',
  );

}